export interface AdminModuleItem {
  id: string
  code: string // '01', '02', ... '14'
  title: string
  shortTitle: string
  description: string
  icon: string
  isAvailable: boolean
  href?: string
  subItems: string[]
}

export const ADMIN_MODULES: AdminModuleItem[] = [
  {
    id: 'dashboard',
    code: '01',
    title: 'Ana Sayfa (Yönetim Dashboard)',
    shortTitle: 'Ana Sayfa',
    description: 'Genel okul istatistikleri, günlük akış, devamsızlık ve sistem uyarıları.',
    icon: 'LayoutDashboard',
    isAvailable: true,
    href: '/m-admin',
    subItems: [
      'Yönetim Dashboard',
      'Okul İstatistikleri',
      'Toplam öğrenci sayısı (348)',
      'Toplam öğretmen sayısı (24)',
      'Sınıf ve şube sayısı (12)',
      'Aktif veli sayısı (312)',
      'Bugünkü Ders Programı',
      'Günlük Devamsızlık Özeti',
      'Yaklaşan Sınavlar ve Etkinlikler',
      'Eksik Öğretmen ve Ders Atama Uyarıları',
      'Ders Programı Çakışma Uyarıları',
      'Son İşlemler',
      'Hızlı Erişim Kısayolları',
    ],
  },
  {
    id: 'students',
    code: '02',
    title: 'Öğrenci Yönetimi',
    shortTitle: 'Öğrenciler',
    description: 'Öğrenci künyeleri, şube dağılımı, kayıt/nakil ve yoklama yönetimi.',
    icon: 'GraduationCap',
    isAvailable: true,
    href: '/m-admin-students',
    subItems: [
      'Öğrenci Listesi',
      'Yeni Öğrenci Ekle',
      'Öğrenci Profilleri',
      'Sınıf ve Şube Atamaları',
      'Kayıt İşlemleri',
      'Nakil İşlemleri',
      'Kayıt Silme / Ayrılma İşlemleri',
      'Öğrenci Numarası ve Hesap Yönetimi',
      'Veli Eşleştirme',
      'Toplu Öğrenci İçe Aktarma (Excel)',
      'Öğrenci Geçmişi ve Önceki Sınıflar',
    ],
  },
  {
    id: 'teachers',
    code: '03',
    title: 'Öğretmen ve Personel Yönetimi',
    shortTitle: 'Öğretmenler',
    description: 'Öğretmen kadrosu, branşlar, rehberlik ve şube ders görevlendirmeleri.',
    icon: 'Briefcase',
    isAvailable: true,
    href: '/m-admin-teachers',
    subItems: [
      'Öğretmen Listesi',
      'Yeni Öğretmen Ekle',
      'Öğretmen Profilleri',
      'Branş ve Uzmanlık Tanımları',
      'Ders Verebileceği Sınıf Seviyeleri',
      'Sınıf Rehber Öğretmeni Atamaları',
      'Öğretmen–Ders Atamaları',
      'Öğretmen–Şube Atamaları',
      'Personel Listesi',
      'Kullanıcı Hesapları',
      'Aktif / Pasif Hesaplar',
      'Toplu Öğretmen İçe Aktarma (Excel)',
    ],
  },
  {
    id: 'schedule',
    code: '04',
    title: 'Ders Programı Yönetimi',
    shortTitle: 'Ders Programı',
    description: 'Haftalık program oluşturma, sürükle-bırak dağıtım ve çakışma kontrolü.',
    icon: 'Calendar',
    isAvailable: true,
    href: '/m-admin-schedule',
    subItems: [
      'Haftalık Ders Programı',
      'Sınıf Bazlı Program',
      'Öğretmen Bazlı Program',
      'Derslik Bazlı Program',
      'Ders Programı Oluştur',
      'Sürükle–Bırak ile Ders Yerleştirme',
      'Ders Saati ve Öğretmen Atamaları',
      'Derslik Atamaları',
      'Öğretmen Çakışma Kontrolü',
      'Derslik Çakışma Kontrolü',
      'Haftalık Ders Saati Kontrolü',
      'Program Taslağı',
      'Programı Yayımla',
      'Program Değişiklik Geçmişi',
    ],
  },
  {
    id: 'classes',
    code: '05',
    title: 'Sınıf ve Şube Yönetimi',
    shortTitle: 'Sınıflar & Şubeler',
    description: 'Kademe seviyeleri (1-8), şubeler, mevcutlar ve sınıf rehber öğretmenleri.',
    icon: 'Building2',
    isAvailable: true,
    href: '/m-admin-classes',
    subItems: [
      'Sınıf Listesi',
      'Yeni Sınıf / Şube Oluştur',
      'Sınıf Seviyeleri (1–8. Sınıf)',
      'Şube Yönetimi (1-A, 1-B vb.)',
      'Sınıf Mevcutları',
      'Sınıf Rehber Öğretmeni Atama',
      'Sınıfa Öğrenci Atama',
      'Sınıf Derslerini Tanımlama',
      'Sınıf Haftalık Ders Saatleri',
      'Derslik Eşleştirmeleri',
      'Önceki Yıl Sınıf Kayıtları',
    ],
  },
  {
    id: 'curriculum',
    code: '06',
    title: 'Dersler ve MEB Müfredatı',
    shortTitle: 'Dersler & Müfredat',
    description: 'MEB kazanımları, üniteler, haftalık ders saatleri ve ortak ders kaynakları.',
    icon: 'BookOpen',
    isAvailable: true,
    href: '/m-admin-curriculum',
    subItems: [
      'Ders Kataloğu',
      'Yeni Ders Ekle',
      'Ders Bilgilerini Düzenle',
      'Sınıf Seviyesine Göre Ders Tanımları',
      'Haftalık Ders Saati Tanımları',
      'Ders–Sınıf Eşleştirmeleri',
      'Müfredat Yönetimi (Üniteler, Konular, Alt Konular)',
      'MEB Kazanımları ve Öğrenme Çıktıları',
      'Müfredat İçe Aktarma',
      'Müfredat Güncelleme ve Sürüm Geçmişi',
      'Ortak Ders Kaynakları',
    ],
  },
  {
    id: 'reports',
    code: '07',
    title: 'Akademik Takip ve Raporlar',
    shortTitle: 'Raporlar & Analiz',
    description: 'Devamsızlık, başarı grafikleri, kazanım analizleri ve PDF/Excel çıktıları.',
    icon: 'BarChart3',
    isAvailable: true,
    href: '/m-admin-reports',
    subItems: [
      'Genel Akademik Raporlar',
      'Devamsızlık Raporları',
      'Öğrenci Başarı Raporları',
      'Sınav Sonuçları',
      'Ödev İstatistikleri',
      'Kazanım Bazlı Öğrenme Durumu',
      'Sınıf Bazlı Başarı Analizi',
      'Sınıflar Arası Karşılaştırmalar',
      'Öğretmen Ders İşleme Takibi',
      'Yoklama İşlem Takibi',
      'PDF Dışa Aktarma',
      'Excel Dışa Aktarma',
    ],
  },
  {
    id: 'parents',
    code: '08',
    title: 'Veli Yönetimi',
    shortTitle: 'Veliler',
    description: 'Veli künyeleri, öğrenci eşleştirmeleri, hesaplar ve iletişim izinleri.',
    icon: 'HeartHandshake',
    isAvailable: false,
    href: '/m-admin-parents',
    subItems: [
      'Veli Listesi',
      'Yeni Veli Ekle',
      'Veli Profilleri',
      'Veli–Öğrenci Eşleştirmeleri',
      'Birden Fazla Öğrenci Bağlama',
      'Veli Hesabı Oluşturma',
      'Hesap Erişim Durumu',
      'İletişim Bilgileri',
      'İletişim İzinleri',
      'Toplu Veli İçe Aktarma (Excel)',
    ],
  },
  {
    id: 'announcements',
    code: '09',
    title: 'Duyurular ve İletişim',
    shortTitle: 'Duyurular & SMS',
    description: 'Okul geneli duyurular, SMS gönderimleri, mobil bildirimler ve hedef kitle.',
    icon: 'Megaphone',
    isAvailable: false,
    href: '/m-admin-announcements',
    subItems: [
      'Duyuru Listesi',
      'Yeni Duyuru Oluştur',
      'Okul Geneli Duyurular',
      'Sınıf ve Şube Duyuruları',
      'Öğretmenlere Özel Duyurular',
      'Veli Bildirimleri',
      'SMS Bildirimleri',
      'Uygulama Bildirimleri',
      'Yayın Tarihi ve Hedef Kitle',
      'Zamanlanmış Duyurular',
      'Gönderim Durumu',
      'Okunma Durumu',
    ],
  },
  {
    id: 'boards',
    code: '10',
    title: 'Akıllı Tahta Yönetimi',
    shortTitle: 'Akıllı Tahtalar',
    description: 'Sınıf tahta eşleştirmeleri, canlı bağlantı durumu, uzaktan kilitleme.',
    icon: 'Tv',
    isAvailable: true,
    href: '/m-admin-boards',
    subItems: [
      'Tahta Listesi',
      'Yeni Tahta Ekle',
      'Tahta–Sınıf Eşleştirmeleri',
      'QR Kod ve Eşleştirme Kodu Yönetimi',
      'Bağlantı Durumu',
      'Son Senkronizasyon Bilgisi',
      'Aktif Ders Oturumları',
      'Uzaktan Tahta Kilitleme',
      'Oturumları Sonlandırma',
      'Kullanılabilir Tahta Araçları',
      'Tahta Kullanım Kayıtları',
    ],
  },
  {
    id: 'library',
    code: '11',
    title: 'Eğitim İçerikleri Yönetimi',
    shortTitle: 'İçerik Kütüphanesi',
    description: 'Eğitsel oyunlar, ders materyalleri, çalışma kağıtları ve video içerikler.',
    icon: 'FolderKanban',
    isAvailable: false,
    href: '/m-admin-library',
    subItems: [
      'İçerik Kütüphanesi',
      'Eğitsel Oyunlar',
      'Ders Materyalleri',
      'Çalışma Kâğıtları',
      'Sunumlar',
      'Video ve Sesli İçerikler',
      'Akıllı Tahta İçerikleri',
      'Yeni İçerik Ekle',
      'Sınıf Seviyesine Göre İçerik Eşleştirme',
      'Ders ve Kazanım Etiketleri',
      'İçerik Yayınlama',
      'İçeriği Yayından Kaldırma',
      'Öğretmenlerle Ortak İçerik Paylaşımı',
    ],
  },
  {
    id: 'calendar',
    code: '12',
    title: 'Okul Yapısı ve Akademik Takvim',
    shortTitle: 'Okul Takvimi',
    description: 'Dönemler, ders saatleri, tatiller, sınav tarihleri ve akademik geçişler.',
    icon: 'CalendarDays',
    isAvailable: false,
    href: '/m-admin-calendar',
    subItems: [
      'Okul Bilgileri',
      'Kurum Ayarları',
      'Akademik Yıl Yönetimi',
      'Dönem Yönetimi',
      'Eğitim Kademeleri',
      'Derslik ve Fiziksel Alanlar',
      'Haftalık Ders Günleri ve Saatleri',
      'Ders Başlangıç ve Bitiş Saatleri',
      'Teneffüs Saatleri',
      'Resmî Tatiller',
      'Okul Tatil Takvimi',
      'Sınav ve Etkinlik Takvimi',
      'Akademik Yıl Geçişi',
    ],
  },
  {
    id: 'security',
    code: '13',
    title: 'Kullanıcı, Yetki ve Güvenlik Yönetimi',
    shortTitle: 'Yetki & Güvenlik',
    description: 'Yönetici hesapları, roller, denetim günlüğü, KVKK ve oturum kayıtları.',
    icon: 'ShieldAlert',
    isAvailable: false,
    href: '/m-admin-security',
    subItems: [
      'Yönetici Hesapları',
      'Müdür ve Müdür Yardımcısı Rolleri',
      'Öğretmen Yetkileri',
      'Öğrenci Yetkileri',
      'Veli Yetkileri',
      'Rol ve İzin Tanımları',
      'Modül Bazlı Erişim Kontrolü',
      'Aktif / Pasif Kullanıcılar',
      'İşlem Kayıtları ve Denetim Günlüğü',
      'Güvenlik Ayarları',
      'Veri Saklama Ayarları',
      'KVKK Süreçleri',
      'Veri Aktarma ve Yedekleme',
      'Oturum ve Erişim Kayıtları',
    ],
  },
  {
    id: 'settings',
    code: '14',
    title: 'Sistem Ayarları',
    shortTitle: 'Sistem Ayarları',
    description: 'Genel yapılandırma, logo/kurumsal kimlik, SMS/E-posta ve entegrasyonlar.',
    icon: 'Settings',
    isAvailable: false,
    href: '/m-admin-settings',
    subItems: [
      'Genel Sistem Ayarları',
      'Okul Logosu ve Kurumsal Kimlik',
      'Bildirim Ayarları',
      'SMS Sağlayıcı Ayarları',
      'E-posta Ayarları',
      'Varsayılan Eğitim Ayarları',
      'Dil ve Görünüm Ayarları',
      'Dosya ve Depolama Ayarları',
      'Entegrasyonlar',
      'Yardım ve Destek',
      'Hata Bildirimi',
      'Sistem Durumu',
    ],
  },
]
